[package]
name = "sign-wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "sign_wasm"
crate-type = ["cdylib"]

[dependencies]
hmac = "0.12"
sha2 = "0.10"
pbkdf2 = "0.12"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wee_alloc = "0.4"
